# permissions to do viewer spools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spool-viewer-role
rules:
- apiGroups:
  - store.vmware.com
  resources:
  - spools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - store.vmware.com
  resources:
  - spools/status
  verbs:
  - get
